# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 930641a225bf37b0994aafc7b369c4a0076a44adcad76c06c27a51d1c3960be1254f9eacd91cdd2719ee1ee5094d25e4cd1bcd9f87059e30f29c5f69c2328036

test:
  secret_key_base: 538aa85608e2677703d05f3270dba344445e0af7d3d34b5a0642035036540302f4bb5419f2f6c63bcbcb5f9b0b6d0d3b66f201df8356b0b652ad9a2fe147f614

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
